services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jobify
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
volumes:
  data: